###################
# # BUILD FOR LOCAL DEVELOPMENT
###################

FROM harbor.mp.gob.bo/registro/dockers/node:24.12.0-alpine AS development
WORKDIR /usr/src/app
ENV TZ=America/La_Paz


COPY package.json ./
COPY . .

RUN npm install
RUN npm run build