###################
# # BUILD FOR LOCAL DEVELOPMENT
###################

FROM harbor.mp.gob.bo/registro/dockers/node:25.6.0-alpine AS development
WORKDIR /usr/src/app
ENV TZ=America/La_Paz


# Habilita Corepack y fuerza Yarn 4.5.3 (según packageManager)
RUN corepack enable && corepack prepare yarn@4.5.3 --activate


COPY package.json ./
COPY yarn.lock ./
COPY . .

RUN yarn install
RUN yarn build